### ISSUE TITLE
Ch11 build code is incomplete and not updated

### ISSUE THREAD

**Issue by jiayihu** [rust-in-action/code#14]
I wasn't able to run the basic starting example. The shown configuration and tools are both incomplete and not updated. When trying to build using `bootimage`, the command is now different (`cargo bootimage`) and in particular there was an error about not being able to find the crate `core`.

It's thus incomplete because `cargo-xbuild` is installed but not actually used. Fortunately, I knew there was another tutorial on writing a kernel with Rust where I found the updated information: https://os.phil-opp.com/minimal-rust-kernel/

Basically, with Rust nightly 2020–07–15, we can now just simply write this in `.cargo/config.toml`:

```toml
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
```

Also this is much better because I was also able, with the latest version which fixed a bug with the nightly toolchain, to continue using rust-analyzer in vscode. OTOH, you are left with no intellisense with `cargo-xbuild`.

I hope this info will be helpful for someone, you can see the source code of the chapter with updated configuration at https://github.com/jiayihu/lab/tree/master/rust/fledge-os

**Comment by timClicks** [comment]
Thanks very much for these comments. I will incorporate these API changes before the book is printed.

**Comment by mgiles** [comment]
Thanks @jiayihu, this is helpful!

I'll add a couple more details on how I got things working on my machine (running macos), in case it's useful to anyone. A lot of the tooling here seems pretty in flux right now, definitely a moving target for the book. Thanks for the effort Tim, even without a perfect path I still found this chapter very enjoyable.

Following [cargo-xbuild's instructions](https://crates.io/crates/cargo-xbuild) ("Alternative: The build-std feature of cargo"), I added the following additional line to `.cargo/config.toml`. Without this, I was getting a build error "rust-lld: error: undefined symbol: memcpy".

```toml
build-std-features = ["compiler-builtins-mem"]
```

The above needs Rust nightly 2020-09-30 or later.

In all, my `.cargo/config.toml` looks like this:

```toml
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "fledge.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
```

and my `Cargo.toml` like this (I needed newer versions of the dependencies to get everything working):

```toml
[package]
name = "ch11-os"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
bootloader = "0.9.11"
x86_64 = "0.12.3"
```

With that configuration, I'm able to build with `cargo build` and run with `cargo run`. `cargo-xbuild` is not used with this configuration and can be uninstalled.

I was able to get VS Code working nicely (proper inline warnings/errors, intellisense working) by installing the `rust-analyzer` extension and using the following `.vscode/settings.json`:

```json
{
  "rust-analyzer.cargo.target": "fledge.json",
  "rust-analyzer.checkOnSave.allTargets": false
}
```
