### ISSUE TITLE
Listing 8. 16 dyn is missing

### ISSUE THREAD

**Issue by mawi1** [rust-in-action/code#18]

**Comment by dmgolembiowski** [comment]
> _No description provided._

Listing 8.16 _Crate metadata for the macgen project_ currently resembles:

```toml
[package]
name = "ch8-macgen"
version = "0.1.0"
authors = ["Tim McNamara <author@rustinaction.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
```
Could you clarify what you mean?
